services:
  db:
    container_name: line-fault-db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: line-fault-db
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 
volumes:
  pgdata: